### ISSUE TITLE
wordseg-dpseg: compilation issues on macos

### ISSUE THREAD

**Issue by mmmaat** [bootphon/wordseg#4]
Compile and run correctly but the dpseg output is not read correctly in python. Text read as '\x' (binary data) instead of '\u' (unicode). See for instance https://travis-ci.org/mmmaat/wordseg/jobs/232483088#L685.

Maybe related to the use of tempfile ? https://github.com/mmmaat/wordseg/blob/master/wordseg/algos/dpseg.py#L143

**Comment by alecristia** [comment]
this may or may not be the same issue (prepared.txt sent to you by email bc too big of an attachment here):

Alejandrinas-MacBook-Air:wordseg acristia$ cat prepared.txt | wordseg-dpseg -f 1 > segmented.dpseg.txt
Traceback (most recent call last):
  File "/anaconda/bin/wordseg-dpseg", line 11, in <module>
    load_entry_point('wordseg==0.6.1', 'console_scripts', 'wordseg-dpseg')()
  File "build/bdist.macosx-10.7-x86_64/egg/wordseg/utils.py", line 178, in __call__
  File "build/bdist.macosx-10.7-x86_64/egg/wordseg/algos/dpseg.py", line 402, in main
  File "build/bdist.macosx-10.7-x86_64/egg/wordseg/algos/dpseg.py", line 337, in <genexpr>
  File "build/bdist.macosx-10.7-x86_64/egg/wordseg/algos/dpseg.py", line 335, in <genexpr>
  File "build/bdist.macosx-10.7-x86_64/egg/wordseg/algos/dpseg.py", line 335, in <genexpr>
KeyError: u'\xe0'

**Comment by mmmaat** [comment]
Ok thank you for the report, yes the issues are linked. I'll need to debug it directly on a mac to fix that...

**Comment by mmmaat** [comment]
From Mac, dpseg and ag can now be used from docker. We do not plan to support it directly.
